services:
  - type: web
    name: my-fastapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: API_KEY
        sync: false
